### ISSUE TITLE
Random connection error blocks everything that is connected.

### ISSUE THREAD

**Issue by kugelkopf123** [iobroker-community-adapters/ioBroker.tr-064#159]
**Describe the bug**  
Random connection errors occur again and again. Sometimes the system runs without problems for several weeks at a time and sometimes there are problems on two consecutive days.
The problems occur randomly. The tr-64 adapter has an error and then blocks the connection of all other adapters. Access to the admin interface of iobroker is no longer possible. Even via SSH it is no longer possible to establish a connection. The only thing that helps in these moments is to pull the plug and restart. 

**To Reproduce**  
Install TR-064 Adapter
Add some Devices that should be checked if they are online
wait for Days...

**Expected behavior**  
That if such an Error happens, that the Adapter automatically restarts so that there is no blocking of the whole system.

**Screenshots & Logfiles**  

```
2020-09-09 02:23:00.777  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 0(Chris-NAS/24:5E:BE:00:FC:0F):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
2020-09-09 02:23:02.005  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:23:02.020  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:23:02.022  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:23:02.023  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:23:04.113  - [32minfo[39m: openweathermap.0 (11182) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.openweathermap, node: v12.18.3, js-controller: 3.1.6
2020-09-09 02:23:29.314  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_1] connection closed: timeout
2020-09-09 02:23:32.556  - [32minfo[39m: sonoff.0 (1984) Client [SonoffDual_R2] connection closed: timeout
2020-09-09 02:23:33.230  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_3] connection closed: timeout
2020-09-09 02:23:35.422  - [32minfo[39m: sonoff.0 (1984) Client [SonoffBasic1] connection closed: timeout
2020-09-09 02:23:36.788  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_2] connection closed: timeout
2020-09-09 02:23:39.034  - [32minfo[39m: influxdb.0 (1847) Connecting http://192.168.1.20:8086 ...
2020-09-09 02:23:40.131  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_4] connection closed: timeout
2020-09-09 02:23:40.859  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 1(Denon-AVR2113/00:05:CD:29:B0:F8):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
2020-09-09 02:23:41.690  - [32minfo[39m: sonoff.0 (1984) Client [ESP32Bachwasserstand] connection closed: timeout
2020-09-09 02:23:42.154  - [31merror[39m: influxdb.0 (1847) Error: connect EHOSTUNREACH 192.168.1.20:8086
2020-09-09 02:23:44.451  - [31merror[39m: openweathermap.0 (11182) uncaught exception: Cannot read property 'statusCode' of undefined
2020-09-09 02:23:44.454  - [31merror[39m: openweathermap.0 (11182) TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/opt/iobroker/node_modules/iobroker.openweathermap/main.js:255:47)
    at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-09-09 02:23:44.969  - [32minfo[39m: openweathermap.0 (11182) terminating
2020-09-09 02:23:44.972  - [32minfo[39m: openweathermap.0 (11182) Terminated (NO_ERROR): Without reason
2020-09-09 02:23:45.504  - [32minfo[39m: host.raspi4 instance system.adapter.openweathermap.0 terminated with code 0 (NO_ERROR)
2020-09-09 02:23:49.267  - [32minfo[39m: sonoff.0 (1984) Client [Shelly1_2] connection closed: timeout
2020-09-09 02:23:49.496  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_6] connection closed: timeout
2020-09-09 02:23:50.220  - [32minfo[39m: sonoff.0 (1984) Client [Shelly25_5] connection closed: timeout
2020-09-09 02:23:52.068  - [32minfo[39m: sonoff.0 (1984) Client [Shelly1_3] connection closed: timeout
2020-09-09 02:23:52.155  - [32minfo[39m: influxdb.0 (1847) Connecting http://192.168.1.20:8086 ...
2020-09-09 02:23:52.697  - [32minfo[39m: sonoff.0 (1984) Client [4ch_OutdoorLights] connection closed: timeout
2020-09-09 02:23:52.750  - [32minfo[39m: influxdb.0 (1847) Not connected to InfluxDB, try later
2020-09-09 02:23:52.769  - [32minfo[39m: sonoff.0 (1984) Client [ESP32SWG] connection closed: timeout
2020-09-09 02:24:23.550  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 2(Klaus-iPhone-5s/40:33:1A:A6:A1:FD):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
2020-09-09 02:25:02.016  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:25:02.017  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:25:02.018  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:25:02.019  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:25:03.617  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 3(Renate-iPhone-8/40:9C:28:7A:CE:22):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
2020-09-09 02:25:45.958  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 4(Renates-iPad-G6/8C:FE:57:80:4F:FE):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
2020-09-09 02:25:56.211  - [31merror[39m: dwd.0 (12331) Empty or invalid JSON: Cannot read JSON file: Error: getaddrinfo EAI_AGAIN www.dwd.de
2020-09-09 02:25:56.726  - [32minfo[39m: dwd.0 (12331) Terminated (NO_ERROR): Without reason
2020-09-09 02:25:57.291  - [32minfo[39m: host.raspi4 instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
2020-09-09 02:26:59.113  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:26:59.114  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:26:59.115  - [31merror[39m: fritzdect.0 (1663) fritzbox returned this {"error":{"errno":"EHOSTUNREACH","code":"EHOSTUNREACH","syscall":"connect","address":"192.168.1.1","port":80},"options":{"url":"http://192.168.1.1/webservices/homeautoswitch.lua?0=0&sid=4edb10f8741b55af&switchcmd=getdevicelistinfos"}}
2020-09-09 02:26:59.116  - [31merror[39m: fritzdect.0 (1663) no response part in returned message
2020-09-09 02:27:06.036  - [33mwarn[39m: tr-064.0 (2214) forEachConfiguredDevice: in GetSpecificHostEntry 6(raspi4/B8:27:EB:EF:A9:EE):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:  - {"code":""}
```

**Versions:**  
 - Adapter version: 4.0.13
 - JS-Controller version: <3.1.6> 
 - Node version: <v12.18.3> 
 - Operating system: <Raspberian Stretch>

**Additional context**  
Perhaps it has something to do with the automatic updates of the Fritzbox.

**Comment by Apollon77** [comment]
I do not think that "The tr-064 adapter has an error" ... I more see that your network has problems ... because all those EHOSTUNREACH and timeouts also from othr adapters are the reason. The tr-064adapter only is "one of those that has a problem reading data over network", so you need to find the issue in your network!

**Comment by kugelkopf123** [comment]
No it hasn’t one. 
It’s definitely the adapter. Had it disable over the summer because I use it to control my heater. 
Never had any problems like this over this time. 
Since 2 weeks I started this adapter again and the problems started over again. 
So...
The ehostunreach are because the router updated its FW at this moment. 
The problem is, that this adapter throws a problem that blocks everything from reconnect despite the fact that the router has long been online again.

And from the influxdb, it’s because my NAS with the dB is in sleep mode over night.

**Comment by Apollon77** [comment]
Sorry but this can not be. The adapter connects to fritzbox .... that’s all. 

So this only happens when Fritzbox is doing an Update?

**Comment by kugelkopf123** [comment]
> Sorry but this can not be. The adapter connects to fritzbox .... that’s all.
> 
> So this only happens when Fritzbox is doing an Update?

I cannot say it with 100% certainty. But the assumption is obvious. 
As already mentioned, it is no longer possible to connect to the admin interface or via SSH. It is only possible for me to check the logs afterwards. Obviously iobroker is still running, but without getting a connection.  
With a normal restart of the Fritzbox this is no problem. I get the usual error messages that the host is not reachable, but after 5-10 minutes after restarting the Fritzbox the Raspi is reachable via the ioBroker Admin interface or via SSH. 
The only thing that has changed was the activation of the tr-064 and the fritzdect adapter.
Since then this error occurs again.

**Comment by Apollon77** [comment]
Did you tried to use only one of both adapters and see if one of them triggers ist. I can only say that both adapters have maaaany installs and noone reports something like this
