### ISSUE TITLE
Error after update 4.2.7

### ISSUE THREAD

**Issue by tobasium** [iobroker-community-adapters/ioBroker.tr-064#223]
After Update to new version adapter starts every 60 seconds.

`

tr-064.0 | 2021-03-08 23:45:07.804 | error | (26147) Cannot read property 'replace' of undefined
-- | -- | -- | --
tr-064.0 | 2021-03-08 23:45:07.803 | error | at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Parser.EventEmitter.emit (domain.js:483:12)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Parser.emit (events.js:314:20)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:55:67
tr-064.0 | 2021-03-08 23:45:07.803 | error | at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:308:37
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Object.forEach (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:260:43)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Object.build (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:159:18)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Object.prep (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:153:32)
tr-064.0 | 2021-03-08 23:45:07.803 | error | at Object.replace (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:142:24)
tr-064.0 | 2021-03-08 23:45:07.803 | error | (26147) TypeError: Cannot read property 'replace' of undefined
tr-064.0 | 2021-03-08 23:45:07.801 | error | (26147) uncaught exception: Cannot read property 'replace' of undefined

`

**Comment by Grothesk242** [comment]
I second that. 

```2021-03-09 08:27:54.676  - info: tr-064.0 (19812) starting. Version 4.2.7 in /opt/iobroker/node_modules/iobroker.tr-064, node: v14.16.0, js-controller: 3.2.16
2021-03-09 08:27:56.022  - error: tr-064.0 (19812) uncaught exception: Cannot read property 'replace' of undefined
2021-03-09 08:27:56.023  - error: tr-064.0 (19812) TypeError: Cannot read property 'replace' of undefined
    at Object.replace (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:142:24)
    at Object.prep (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:153:32)
    at Object.build (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:159:18)
    at Object.forEach (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:260:43)
    at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:308:37
    at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:55:67
    at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    at Parser.EventEmitter.emit (domain.js:467:12)
    at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26)
2021-03-09 08:27:56.023  - error: tr-064.0 (19812) Cannot read property 'replace' of undefined
2021-03-09 08:27:56.040  - info: tr-064.0 (19812) terminating
2021-03-09 08:27:56.041  - warn: tr-064.0 (19812) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-03-09 08:27:56.541  - error: host.raspberrypi Caught by controller[0]: TypeError: Cannot read property 'replace' of undefined
2021-03-09 08:27:56.543  - error: host.raspberrypi Caught by controller[0]:     at Object.replace (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:142:24)
2021-03-09 08:27:56.544  - error: host.raspberrypi Caught by controller[0]:     at Object.prep (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:153:32)
2021-03-09 08:27:56.544  - error: host.raspberrypi Caught by controller[0]:     at Object.build (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:159:18)
2021-03-09 08:27:56.545  - error: host.raspberrypi Caught by controller[0]:     at Object.forEach (/opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:260:43)
2021-03-09 08:27:56.546  - error: host.raspberrypi Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:308:37
2021-03-09 08:27:56.546  - error: host.raspberrypi Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.tr-064/lib/calllist.js:55:67
2021-03-09 08:27:56.547  - error: host.raspberrypi Caught by controller[0]:     at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18)
2021-03-09 08:27:56.548  - error: host.raspberrypi Caught by controller[0]:     at Parser.emit (events.js:315:20)
2021-03-09 08:27:56.548  - error: host.raspberrypi Caught by controller[0]:     at Parser.EventEmitter.emit (domain.js:467:12)
2021-03-09 08:27:56.549  - error: host.raspberrypi Caught by controller[0]:     at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26)
2021-03-09 08:27:56.550  - error: host.raspberrypi instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-03-09 08:27:56.551  - info: host.raspberrypi Restart adapter system.adapter.tr-064.0 because enabled
```

**Comment by Apollon77** [comment]
4.2.8 comes out. If this also not helps I need a debug log
