### ISSUE TITLE
Verbindung zu Fritzbox Anruferdiensten bricht nach einiger Zeit ab

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.tr-064#576]
**Describe the bug**  
Der Adapter registriert nach einiger Zeit nicht mehr dass Anrufe eingehen, erfasst keine verpassten Anrufe mehr und aktualisiert bis zu einem Neustart die Anruflisten nicht mehr.
Wenn ich den Adapter händisch neu starte, funktioniert es wieder eine gewisse Zeit.

**To Reproduce**  
Der Fehler lässt sich bei mir beliebig oft reproduzieren. Eine zeit lang funktioniert die Anruf / Anruflisten Funktion und dann nicht mehr.

**Expected behavior**  
Ich  würde erwarten, dass der Adapter einfach verbunden bleibt.

**Screenshots & Logfiles**  
`2024-12-09 09:19:24.058 - debug: tr-064.0 (111881) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-12-09 09:19:24.149 - debug: tr-064.0 (111881) Objects client ready ... initialize now
2024-12-09 09:19:24.205 - debug: tr-064.0 (111881) Objects create System PubSub Client
2024-12-09 09:19:24.206 - debug: tr-064.0 (111881) Objects create User PubSub Client
2024-12-09 09:19:24.445 - debug: tr-064.0 (111881) Objects client initialize lua scripts
2024-12-09 09:19:24.455 - debug: tr-064.0 (111881) Objects connected to redis: 127.0.0.1:9001
2024-12-09 09:19:24.567 - debug: tr-064.0 (111881) Redis States: Use Redis connection: 127.0.0.1:9000
2024-12-09 09:19:24.649 - debug: tr-064.0 (111881) States create System PubSub Client
2024-12-09 09:19:24.650 - debug: tr-064.0 (111881) States create User PubSub Client
2024-12-09 09:19:24.868 - debug: tr-064.0 (111881) States connected to redis: 127.0.0.1:9000
2024-12-09 09:19:25.011 - debug: tr-064.0 (111881) Plugin sentry Do not initialize Plugin (enabled=false)
2024-12-09 09:19:25.275 - info: tr-064.0 (111881) starting. Version 4.3.0 in /opt/iobroker/node_modules/iobroker.tr-064, node: v20.18.0, js-controller: 7.0.3
2024-12-09 09:19:25.311 - debug: tr-064.0 (111881) Calllist Config after normalizing: {"all":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"missed":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"outbound":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"inbound":{"generateJson":true,"generateHtml":true,"maxEntries":"10"},"use":true}
2024-12-09 09:19:25.669 - debug: tr-064.0 (111881) Set Template: "The last call was from %(name) at %(date) from %(caller)%(type): %(count)%(date)%(name)%(caller)" | %(date) | %(name) | %(caller)
%(date) | %(name) | %(caller)
2024-12-09 09:19:26.293 - debug: tr-064.0 (111881) Initialize HTML template:The last call was from %(name) at %(date) from %(caller)%(type): %(count)%(date)%(name)%(caller) | %(date) | %(name) | %(caller)
%(date) | %(name) | %(caller)
2024-12-09 09:19:26.295 - debug: tr-064.0 (111881) createConfiguredDevices
2024-12-09 09:19:26.295 - debug: tr-064.0 (111881) forEachConfiguredDevice
2024-12-09 09:19:26.405 - debug: tr-064.0 (111881) Request Calllist JSON: url = http://192.168.2.1:49000/calllist.lua?sid=4a222cd48d0edeb2×tamp=1356917147&id=8243
2024-12-09 09:19:26.411 - debug: tr-064.0 (111881) getVoIPCommonCountryCode: 0049
2024-12-09 09:19:26.468 - debug: tr-064.0 (111881) getVoIPCommonAreaCode: 09502
2024-12-09 09:19:26.469 - debug: tr-064.0 (111881) Phonebook.read
2024-12-09 09:19:26.585 - debug: tr-064.0 (111881) Phonebook.read: NewPhonebookList=0,1
2024-12-09 09:19:26.638 - debug: tr-064.0 (111881) Phonebook 0: {"NewPhonebookName":"Telefonbuch","NewPhonebookExtraID":"","NewPhonebookURL":"http://192.168.2.1:49000/phonebook.lua?sid=4a222cd48d0edeb2&pbid=0"} / err=null
2024-12-09 09:19:27.074 - debug: tr-064.0 (111881) Result Calllist JSON: {"root":{"timestamp":"1356917147"}}
2024-12-09 09:19:27.075 - debug: tr-064.0 (111881) Calllist all regenerated
2024-12-09 09:19:27.076 - debug: tr-064.0 (111881) Calllist inbound regenerated
2024-12-09 09:19:27.076 - debug: tr-064.0 (111881) Calllist missed regenerated
2024-12-09 09:19:27.076 - debug: tr-064.0 (111881) Calllist outbound regenerated
2024-12-09 09:19:27.077 - debug: tr-064.0 (111881) Calllist states updated
2024-12-09 09:19:28.338 - debug: tr-064.0 (111881) starting callmonitor
2024-12-09 09:19:28.339 - debug: tr-064.0 (111881) callmonitor initialize ...
2024-12-09 09:19:28.343 - debug: tr-064.0 (111881) callmonitor connected
2024-12-09 09:19:30.340 - debug: tr-064.0 (111881) in updateAll
2024-12-09 09:20:01.253 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:04:31.080 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:05:01.859 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:05:32.505 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:06:03.380 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:06:34.334 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:06:58.807 - debug: tr-064.0 (111881) State changed: tr-064.0.states.ring = {"val":"**610 ,10","ack":false,"ts":1733742418722,"q":0,"c":"script.js.Wandtablet.Klingel_Haustüre","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1733742418722}
2024-12-09 12:06:58.808 - debug: tr-064.0 (111881) Ring : ["**610 ","10"]
2024-12-09 12:07:05.259 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:07:08.749 - debug: tr-064.0 (111881) State changed: tr-064.0.states.ring = {"val":"**613 ,10","ack":false,"ts":1733742428722,"q":0,"c":"script.js.Wandtablet.Klingel_Haustüre","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1733742428722}
2024-12-09 12:07:08.750 - debug: tr-064.0 (111881) Ring : ["**613 ","10"]
2024-12-09 12:07:10.443 - debug: tr-064.0 (111881) End Ring after 10s
2024-12-09 12:07:20.293 - debug: tr-064.0 (111881) End Ring after 10s
2024-12-09 12:07:35.824 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:08:06.826 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:08:38.230 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:09:09.204 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:09:40.120 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:10:10.932 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:10:41.871 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:11:12.741 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:11:43.794 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:12:14.836 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:12:45.721 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:13:16.620 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:13:47.596 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:14:18.423 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:14:49.560 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:15:20.632 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:15:51.722 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:16:22.811 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:16:53.738 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:17:24.676 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:43:13.312 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:43:44.241 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:44:15.011 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:44:46.054 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:45:17.037 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:45:47.731 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:46:18.390 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:46:49.369 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:47:20.210 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:47:51.349 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:48:22.528 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:48:53.458 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:49:24.464 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:49:55.543 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:50:26.711 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:50:57.697 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:51:28.704 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:51:59.620 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:52:30.533 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:53:01.321 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:53:32.553 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:54:03.421 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:54:34.421 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:55:05.273 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:55:36.254 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:56:07.257 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:56:38.482 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:57:09.423 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:57:40.345 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:58:11.224 - debug: tr-064.0 (111881) in updateAll
2024-12-09 12:58:42.183 - debug: tr-064.0 (111881) in updateAll

</body>
</html>

`
**Versions:**  
 - Adapter version: 4.3.0
 - JS-Controller version: 7.0.3
 - Node version: 20.18.0
 - Operating system: debian

**Additional context**  
Folgendes habe ich schon ohne Erfolg versucht:
- Adapter gelöscht und neu installiert
- Adapter auf einem Anderen System neu aufgesetzt
- sämtliche Einstellungen verändert
- Fritzbox Nuter gelöscht und neu angelegt
- Verschiedene Benutzer für verschiedene Dienste
- Fritzbox neu aufgesetzt (OS 8) auf FB 7590

Der Fritzbox Callmonitor für mein Android Handy funktioniert tadellos, und im Debug log macht er brav sein updateAll nur wird bis zum manuellen Neustart des Adapters nicht mehr geupdatet

**Comment by Apollon77** [comment]
Hm ... hast Du eine Idee wie man rauskriegen könnte woran es liegt? Also hier sieht man das es nach 3h noch tut ... ist es immer ungefähr so lange oder länger/kürzer? Er bleibt auch verbiunden, scheinbar sendet Fritzbox  aber keine Daten mehr. man könnte höchstens zb stündlich neu verbinden oder so

**Comment by peoples0815** [comment]
Ich finde keine Ereignis das regelmäßig auftritt oder irgendwelche Rückschlüsse auf den Grund geben könnte.
Auch die Zeit ist total unterschiedlich, manchmal ein paar Stunden manchmal ein paar minuten. Wenn ich den Adapter automatisch neu starte, funktioniert das nicht immer. Wenn ich ihn händisch durch klicken auf den "Reload-Button" neu starte funktioniert das immer.

**Comment by mcm1957** [comment]
Please check with current version 5.0.0

**Comment by Wildbill-Z** [comment]
With 5.0.1 (latest) adapter won't start anymore:

`
tr-064.0
2026-09-10 09:23:31.362	error	TypeError: Cannot read properties of undefined (reading 'safe') at getWLAN (/opt/iobroker/node_modules/iobroker.tr-064/build/lib/tr064.js:447:14) at doIt (/opt/iobroker/node_modules/iobroker.tr-064/build/main.js:537:13) at Timeout._onTimeout (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:1462:7) at listOnTimeout (node:internal/timers:585:17) at process.processTimers (node:internal/timers:521:7)

tr-064.0
2026-09-10 09:23:31.360	error	uncaught exception: Cannot read properties of undefined (reading 'safe')

tr-064.0
2026-09-10 09:23:27.619	info	starting. Version 5.0.1 in /opt/iobroker/node_modules/iobroker.tr-064, node: v22.23.2, js-controller: 7.2.2

host.iobroker-vm
2026-09-10 09:22:56.625	error	instance system.adapter.tr-064.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

tr-064.0
2026-09-10 09:22:56.590	info	terminating

tr-064.0
2026-09-10 09:22:56.589	info	terminating

tr-064.0
2026-09-10 09:22:56.089	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

tr-064.0
2026-09-10 09:22:56.088	info	terminating

tr-064.0
2026-09-10 09:22:56.086	error	Cannot read properties of undefined (reading 'safe')

tr-064.0
2026-09-10 09:22:56.086	error	TypeError: Cannot read properties of undefined (reading 'safe') at getWLAN (/opt/iobroker/node_modules/iobroker.tr-064/build/lib/tr064.js:447:14) at doIt (/opt/iobroker/node_modules/iobroker.tr-064/build/main.js:537:13) at Timeout._onTimeout (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:1462:7) at listOnTimeout (node:internal/timers:585:17) at process.processTimers (node:internal/timers:521:7)

tr-064.0
2026-09-10 09:22:56.085	error	uncaught exception: Cannot read properties of undefined (reading 'safe')

tr-064.0
2026-09-10 09:22:52.387	info	starting. Version 5.0.1 in /opt/iobroker/node_modules/iobroker.tr-064, node: v22.23.2, js-controller: 7.2.2

`

Back to 4.3.0 (stable) it starts again without problems.

Sorry, forgot:
Admin version 8.0.11
JS-Controller version 7.2.2
Node version v22.23.2

**Comment by mcm1957** [comment]
@GermanBluefox release 5.0.2. Plese recheck

**Comment by Wildbill-Z** [comment]
5.0.2 installed and started without problem. I disabled my cron to restart the adapter every hour and will see, if it will work permanently.

Thanks

**Comment by Wildbill-Z** [comment]
Still after 2 hours without restart or anything, the adapter is working as expected. I think, this issue can be closed ( I can‘t close it as it is not mine)

**Comment by mcm1957** [comment]
If this problem or some similar issue occures again, please open a new issue.
