### ISSUE TITLE
3.1.1: callMonitor.close is not a function

### ISSUE THREAD

**Issue by darkiop** [iobroker-community-adapters/ioBroker.tr-064#91]
With 3.1.1 there are the following errors for some options of the adapter (e.g. call monitor, call forwarding, ...):

`2020-01-26 06:59:10.775  - warn: tr-064.0 (25769) States system pmessage io.system.adapter.tr-064.0.sigKill {"val":-1,"ack":false,"ts":1580018350765,"q":0,"from":"system.host.iobroker-master","lc":15│
2020-01-26 06:59:10.778  - warn: tr-064.0 (25769) TypeError: callMonitor.close is not a function                                                                                                       │
    at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.tr-064/main.js:117:36)                                                                                                                  │
    at Adapter.emit (events.js:198:13)                                                                                                                                                                 │
    at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7223:22)                                                                                                                 │
    at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4712:25)                                                                                                               │
    at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)                                                                 │
    at runCallback (timers.js:705:18)                                                                                                                                                                  │
    at tryOnImmediate (timers.js:676:5)   `

**Comment by Apollon77** [comment]
should be fixed in 3.1.3
