### ISSUE TITLE
uncaught exception: fndest is not defined Instance is not starting anymore

### ISSUE THREAD

**Issue by mk176** [iobroker-community-adapters/ioBroker.tr-064#94]
**Describe the bug**  
With new 3.1.1 version the instance is not starting anymore on windows with node.js 10.18.1 or node.js 12.14.1. 

**Screenshots & Logfiles**  

2020-01-26 11:31:05.800  - info: host.Server instance system.adapter.tr-064.0 started with pid 17112
--
2020-01-26 11:31:06.818  - info: tr-064.0 (17112) starting. Version 3.1.1 in C:/Program Files/iobroker/node_modules/iobroker.tr-064, node: v10.18.1
2020-01-26 11:31:07.402  - error: tr-064.0 (17112) uncaught exception: fndest is not defined
2020-01-26 11:31:07.402  - error: tr-064.0 (17112) ReferenceError: fndest is not defined
at ar.forEach.fn (C:\Program Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:149:37)
at Array.forEach ()
at getFunctions (C:\Program Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:149:12)
at Deflections.init (C:\Program Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:156:17)
at new Deflections (C:\Program Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:21:10)
at tr064Client.init.err (C:\Program Files\iobroker\node_modules\iobroker.tr-064\main.js:1144:27)
at C:\Program Files\iobroker\node_modules\iobroker.tr-064\main.js:82:28
at C:\Program Files\iobroker\node_modules\iobroker.tr-064\node_modules\tr-O64\lib\Service.js:267:17
at Parser. (C:\Program Files\iobroker\node_modules\iobroker.tr-064\node_modules\xml2js\lib\parser.js:304:18)
at Parser.emit (events.js:198:13)
2020-01-26 11:31:07.907  - info: tr-064.0 (17112) terminating
2020-01-26 11:31:07.909  - info: tr-064.0 (17112) Terminated (NO_ERROR): Without reason
2020-01-26 11:31:08.425  - error: host.Server Caught by controller[0]: ReferenceError: fndest is not defined
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at ar.forEach.fn (C:\Program  Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:149:37)
2020-01-26 11:31:08.425  - error: host.Server Caught by controller[0]:     at Array.forEach ()
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at getFunctions (C:\Program  Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:149:12)
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at Deflections.init  (C:\Program  Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:156:17)
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at new Deflections (C:\Program  Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:21:10)
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at tr064Client.init.err  (C:\Program Files\iobroker\node_modules\iobroker.tr-064\main.js:1144:27)
2020-01-26 11:31:08.425  - error: host.Server Caught by controller[0]:     at C:\Program Files\iobroker\node_modules\iobroker.tr-064\main.js:82:28
2020-01-26 11:31:08.425  - error:  host.Server Caught by controller[0]:     at C:\Program  Files\iobroker\node_modules\iobroker.tr-064\node_modules\tr-O64\lib\Service.js:267:17
2020-01-26 11:31:08.425  - error: host.Server Caught by controller[0]:     at Parser. (C:\Program Files\iobroker\node_modules\iobroker.tr-064\node_modules\xml2js\lib\parser.js:304:18)
2020-01-26 11:31:08.426  - error: host.Server Caught by controller[0]:     at Parser.emit (events.js:198:13)
2020-01-26 11:31:08.426  - info: host.Server instance system.adapter.tr-064.0 terminated with code 0 (NO_ERROR)

**Versions:**  
 - Adapter version: 3.1.1
 - JS-Controller version: 2.28
 - Node version: 10.18.1 and 12.14.1
 - Operating system: Windows 10 1909

**Additional context**

**Comment by Ilovegym66** [comment]
here the same, one time the error message "no config found" comes.. but there is a config, and I saved the config again, same again.
Node 10.18.0, NPM 6.13.4, js-controller 2.2.8, Adapter 3.1.1, Linux Mint 18.3.

**Comment by jlegen** [comment]
got the same, looks like a typo: removing "fn" from "fndest" helped... ;-)
(in your file: C:\Program Files\iobroker\node_modules\iobroker.tr-064\lib\deflections.js:149)

**Comment by Diginix** [comment]
Same here with Linux.
Modified iobroker/node_modules/iobroker.tr-064/lib/deflections.js:149 helps.

**Comment by Apollon77** [comment]
should be fixed in 3.1.2
